"use client";
import React, { useState } from "react";
import type { ScreeningInput, DerivedInput } from "@/lib/types";
import type { TrialDef, TrialResult } from "@/lib/trials/types";

interface Props {
  input: ScreeningInput;
  derived: DerivedInput;
  results: { trial: TrialDef; result: TrialResult }[];
}

function fmtNum(n: number | null | undefined, suffix = ""): string {
  if (n === null || n === undefined || Number.isNaN(n)) return "—";
  return `${n}${suffix}`;
}

function fmtHours(h: number | null): string {
  if (h === null) return "—";
  return `${h.toFixed(1)} h`;
}

function buildSummary({ input, derived, results }: Props): string {
  const lines: string[] = [];
  const ts = new Date().toLocaleString();
  lines.push(`Stroke Trial Screening — ${ts}`);
  lines.push(`(No PHI — clinical fields only)`);
  lines.push("");

  lines.push("CLINICAL");
  lines.push(`  Age: ${fmtNum(input.age)}   Sex: ${input.sex === "unknown" ? "—" : input.sex}`);
  lines.push(`  Premorbid mRS: ${fmtNum(input.pre_mrs)}`);
  lines.push(`  NIHSS total: ${fmtNum(derived.nihss_total)}${derived.nihss_complete ? "" : " (incomplete)"}`);
  lines.push(
    `  Onset: ${input.wakeup_status ?? "—"}   LKWT: ${input.lkw_time ?? "—"}   Now: ${input.current_time}`
  );
  lines.push(`  LKWT → now: ${fmtHours(derived.lkw_to_now_hours)}`);
  if (input.wakeup_status === "wakeup") {
    lines.push(`  Discovery < 6h before arrival: ${input.wakeup_discovery_lt6h}`);
  }
  lines.push(
    `  Glucose: ${fmtNum(input.glucose_mgdl, " mg/dL")}   INR: ${fmtNum(input.inr)}   Plt: ${fmtNum(input.platelets_per_uL, "/μL")}`
  );
  lines.push(`  BP: ${fmtNum(input.sbp)}/${fmtNum(input.dbp)}${input.thrombolysis_planned ? " (lytics planned)" : ""}`);
  lines.push("");

  lines.push("IMAGING");
  lines.push(`  Modality: ${input.imaging_modality ?? "—"}   ASPECTS: ${fmtNum(input.aspects)}   Imaging age: ${fmtNum(input.imaging_age_minutes, " min")}`);
  lines.push(`  Occlusion: ${input.occlusion_site}   Midline shift: ${fmtNum(input.midline_shift_mm, " mm")}`);
  lines.push("");

  lines.push("ELIGIBILITY");
  for (const { trial, result } of results) {
    const arm = result.matched_arm_name ? ` — arm: ${result.matched_arm_name}` : "";
    lines.push(`  ${trial.short_name}: ${result.status.replace(/_/g, " ").toUpperCase()}${arm}`);
    if (trial.id === "we-trust" && (result.status === "eligible" || result.status === "eligible_with_warnings")) {
      lines.push(`    → DIRECT TO ANGIO SUITE — skip CT.`);
    }
    if (result.failing.length > 0) {
      lines.push(`    Fails:`);
      for (const c of result.failing) lines.push(`      • ${c.label}`);
    }
    if (result.warnings.length > 0) {
      lines.push(`    Warnings:`);
      for (const c of result.warnings) lines.push(`      • ${c.label}`);
    }
    if (result.pending.length > 0) {
      lines.push(`    Need: ${result.pending.map((c) => c.label).join("; ")}`);
    }
  }

  lines.push("");
  lines.push("ATTENDING DECISION");
  if (input.attending_decision) {
    lines.push(
      `  Decision: ${input.attending_decision.toUpperCase()}   Time: ${input.attending_decision_time ?? "—"}   Attending: ${input.attending_name || "—"}`
    );
    if (input.attending_notes) {
      lines.push(`  Notes: ${input.attending_notes}`);
    }
  } else {
    lines.push("  No decision recorded.");
  }

  lines.push("");
  lines.push("Generated by Stroke Trial Screener (Dr. SK Lee, Montefiore NIR).");
  return lines.join("\n");
}

export function CopyableSummary(props: Props) {
  const [copied, setCopied] = useState(false);
  const text = buildSummary(props);

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // older browser fallback
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand("copy");
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } finally {
        document.body.removeChild(ta);
      }
    }
  };

  return (
    <section className="bg-white rounded-lg border border-gray-200 p-4 mb-4">
      <header className="flex items-center justify-between mb-2">
        <h2 className="text-base font-bold text-brand">Summary (copyable)</h2>
        <button
          type="button"
          onClick={onCopy}
          className="px-3 py-1.5 text-xs font-semibold rounded bg-brand text-white hover:bg-brand-dark transition-colors no-print"
        >
          {copied ? "Copied ✓" : "Copy to clipboard"}
        </button>
      </header>
      <pre className="bg-gray-50 border border-gray-200 rounded p-3 text-xs text-gray-800 whitespace-pre-wrap font-mono">
        {text}
      </pre>
    </section>
  );
}
